# DELETE http://localhost:3001/api/persons/68ede772a0c35a70b196a15f


# GET http://localhost:3001/api/persons


POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "gopal",
    "number": "01-4255453"
}